<a href="https://www.kaggle.com/code/tunguz/tps-jan-2021-with-ridge?scriptVersionId=109844776" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
from sklearn.linear_model import Ridge
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold
from tqdm import tqdm_notebook as tqdm
import datetime
from sklearn.metrics import mean_squared_error, mean_absolute_error
import gc
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/tabular-playground-series-jan-2021/sample_submission.csv
/kaggle/input/tabular-playground-series-jan-2021/train.csv
/kaggle/input/tabular-playground-series-jan-2021/test.csv


In [2]:
train = pd.read_csv("/kaggle/input/tabular-playground-series-jan-2021/train.csv")
test = pd.read_csv("/kaggle/input/tabular-playground-series-jan-2021/test.csv")
sample_submission = pd.read_csv('../input/tabular-playground-series-jan-2021/sample_submission.csv')

In [3]:
train.head()

id     cont1     cont2     cont3     cont4     cont5     cont6     cont7  \
0   1  0.670390  0.811300  0.643968  0.291791  0.284117  0.855953  0.890700   
1   3  0.388053  0.621104  0.686102  0.501149  0.643790  0.449805  0.510824   
2   4  0.834950  0.227436  0.301584  0.293408  0.606839  0.829175  0.506143   
3   5  0.820708  0.160155  0.546887  0.726104  0.282444  0.785108  0.752758   
4   8  0.935278  0.421235  0.303801  0.880214  0.665610  0.830131  0.487113   

      cont8     cont9    cont10    cont11    cont12    cont13    cont14  \
0  0.285542  0.558245  0.779418  0.921832  0.866772  0.878733  0.305411   
1  0.580748  0.418335  0.432632  0.439872  0.434971  0.369957  0.369484   
2  0.558771  0.587603  0.823312  0.567007  0.677708  0.882938  0.303047   
3  0.823267  0.574466  0.580843  0.769594  0.818143  0.914281  0.279528   
4  0.604157  0.874658  0.863427  0.983575  0.900464  0.935918  0.435772   

     target  
0  7.243043  
1  8.203331  
2  7.776091  
3  6.957716  
4  7.951046

In [4]:
train.describe()

id          cont1          cont2          cont3  \
count  300000.000000  300000.000000  300000.000000  300000.000000   
mean   249825.145857       0.506873       0.497898       0.521557   
std    144476.732562       0.203976       0.228159       0.200770   
min         1.000000      -0.082263      -0.031397       0.020967   
25%    124656.500000       0.343078       0.319170       0.344096   
50%    249738.500000       0.484005       0.553209       0.551471   
75%    374836.250000       0.643789       0.731263       0.648315   
max    499999.000000       1.016227       0.859697       1.006955   

               cont4          cont5          cont6          cont7  \
count  300000.000000  300000.000000  300000.000000  300000.000000   
mean        0.515683       0.502022       0.526515       0.487890   
std         0.233035       0.220701       0.217909       0.181096   
min         0.152761       0.276377       0.066166      -0.097666   
25%         0.294935       0.284108       0.356163       0.346600   
50%         0.482880       0.451733       0.470988       0.466825   
75%         0.748705       0.670660       0.694043       0.581292   
max         1.010402       1.034261       1.043858       1.066167   

               cont8          cont9         cont10         cont11  \
count  300000.000000  300000.000000  300000.000000  300000.000000   
mean        0.525163       0.459857       0.520532       0.483926   
std         0.216221       0.196685       0.201854       0.220082   
min         0.217260      -0.240604      -0.085046       0.083277   
25%         0.341486       0.330832       0.375465       0.300474   
50%         0.483460       0.416843       0.458877       0.441916   
75%         0.685250       0.575041       0.700292       0.679128   
max         1.024427       1.004114       1.199951       1.022620   

              cont12         cont13         cont14         target  
count  300000.000000  300000.000000  300000.000000  300000.000000  
mean        0.506877       0.553442       0.503713       7.905661  
std         0.218947       0.229730       0.208238       0.733071  
min         0.088635       0.029950       0.166367       0.000000  
25%         0.310166       0.350472       0.308673       7.329367  
50%         0.486599       0.487707       0.431845       7.940571  
75%         0.694453       0.768479       0.712653       8.470084  
max         1.049025       0.977845       0.868506      10.267569

In [5]:
train.isna().sum()

id        0
cont1     0
cont2     0
cont3     0
cont4     0
cont5     0
cont6     0
cont7     0
cont8     0
cont9     0
cont10    0
cont11    0
cont12    0
cont13    0
cont14    0
target    0
dtype: int64

In [6]:
#profile = ProfileReport(train, title='Train Profiling Report', html={'style':{'full_width':True}})

In [7]:
#profile

In [8]:
test.head()

id     cont1     cont2     cont3     cont4     cont5     cont6     cont7  \
0   0  0.353600  0.738780  0.600939  0.293377  0.285691  0.458006  0.620704   
1   2  0.907222  0.189756  0.215531  0.869915  0.301333  0.528958  0.390351   
2   6  0.179287  0.355353  0.623972  0.437812  0.282476  0.320826  0.386789   
3   7  0.359385  0.181049  0.551368  0.206386  0.280763  0.482076  0.506677   
4  10  0.335791  0.682607  0.676481  0.219465  0.282861  0.581721  0.748639   

      cont8     cont9    cont10    cont11    cont12    cont13    cont14  
0  0.422249  0.369203  0.435727  0.550540  0.699134  0.286864  0.364515  
1  0.521112  0.794779  0.798580  0.446475  0.449037  0.916964  0.513002  
2  0.776422  0.222268  0.229102  0.211913  0.222651  0.327164  0.827941  
3  0.362793  0.379737  0.345686  0.445276  0.518485  0.299028  0.598166  
4  0.350158  0.448915  0.506878  0.817721  0.805895  0.790591  0.249275

In [9]:
test.describe()

id          cont1          cont2          cont3  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean   250261.031215       0.507222       0.498080       0.521381   
std    144128.894365       0.204220       0.227866       0.200656   
min         0.000000      -0.061638      -0.030548       0.040867   
25%    125538.250000       0.343649       0.322703       0.344251   
50%    250389.500000       0.484292       0.553147       0.551413   
75%    375240.250000       0.644079       0.686518       0.648656   
max    499990.000000       1.017577       0.853813       1.001791   

               cont4          cont5          cont6          cont7  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        0.514801       0.502274       0.526987       0.487722   
std         0.232995       0.220812       0.218145       0.180805   
min         0.153318       0.276679       0.075104      -0.024760   
25%         0.294361       0.284113       0.356357       0.347336   
50%         0.482019       0.451960       0.471000       0.466392   
75%         0.747133       0.670831       0.694422       0.580666   
max         0.997446       1.033722       1.046715       1.054225   

               cont8          cont9         cont10         cont11  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        0.525284       0.460257       0.520478       0.484187   
std         0.216084       0.197217       0.201645       0.219972   
min         0.219631      -0.231308      -0.109759       0.078859   
25%         0.342148       0.330739       0.375496       0.301236   
50%         0.483781       0.416900       0.458622       0.442037   
75%         0.685070       0.575248       0.700157       0.677691   
max         1.026280       1.001405       1.140639       1.023151   

              cont12         cont13         cont14  
count  200000.000000  200000.000000  200000.000000  
mean        0.506763       0.554390       0.503174  
std         0.218598       0.229730       0.208333  
min         0.094504       0.015367       0.164500  
25%         0.310875       0.350956       0.308210  
50%         0.485527       0.491538       0.431124  
75%         0.694630       0.769323       0.712664  
max         1.049417       0.977223       0.868679

In [10]:
test.isna().sum()

id        0
cont1     0
cont2     0
cont3     0
cont4     0
cont5     0
cont6     0
cont7     0
cont8     0
cont9     0
cont10    0
cont11    0
cont12    0
cont13    0
cont14    0
dtype: int64

In [11]:
sample_submission.head()

id  target
0   0     0.5
1   2     0.5
2   6     0.5
3   7     0.5
4  10     0.5

In [12]:
target = train['target'].values

In [13]:
np.mean(target)

7.905661328316825

In [14]:
target_mean = np.mean(target)

In [15]:
np.std(target)

0.7330696085805829

In [16]:
columns = test.columns[1:]

In [17]:
np.unique(target).shape


(299811,)

In [18]:
target.shape

(300000,)

In [19]:
train_oof = np.zeros((300000,))
test_preds = 0
train_oof.shape

(300000,)

In [20]:
target -= target_mean
target

array([-0.66261874,  0.29766981, -0.12957057, ...,  1.6868252 ,
        0.30228927,  0.98462348])

In [21]:
NUM_FOLDS = 10
kf = KFold(n_splits=NUM_FOLDS, shuffle=True, random_state=0)

for f, (train_ind, val_ind) in tqdm(enumerate(kf.split(train, target))):
        #print(f'Fold {f}')
        train_df, val_df = train.iloc[train_ind][columns], train.iloc[val_ind][columns]
        train_target, val_target = target[train_ind], target[val_ind]
        
        model = Ridge()
        model.fit(train_df, train_target)
        temp_oof = model.predict(val_df)
        temp_test = model.predict(test[columns])

        train_oof[val_ind] = temp_oof
        test_preds += temp_test/NUM_FOLDS

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  after removing the cwd from sys.path.


|          | 0/? [00:00<?, ?it/s]

In [22]:
train_oof

array([ 0.10562165,  0.08516232, -0.1743787 , ...,  0.08977555,
        0.13519832, -0.0618333 ])

In [23]:
test_preds

array([ 0.1480571 , -0.30825114,  0.04520694, ..., -0.049733  ,
        0.03178279,  0.05011721])

In [24]:
train_oof += target_mean


In [25]:
target += target_mean

In [26]:
test_preds += target_mean

In [27]:
mean_squared_error(train_oof, target, squared=False)

0.7262345616787338

In [28]:
np.save('train_oof', train_oof)
np.save('test_preds', test_preds)

In [29]:
test_preds

array([8.05371843, 7.59741019, 7.95086827, ..., 7.85592833, 7.93744412,
       7.95577854])

In [30]:
sample_submission['target'] = test_preds
sample_submission.to_csv('submission.csv', index=False)